var securitycode = document.getElementsByClassName("code")[0]
var image = document.getElementsByClassName("base-image")[0]
var binbox = document.getElementById("binbox");
var textbox = document.getElementById("locationtext")
securitycode.addEventListener('input', function (e) {
    console.log(securitycode.textContent)
    if (securitycode.textContent = "1013") {
        console.log("security authorized")
        image.style.visibility = "visible"
    }
})


var obj = [ 
{ binnum: 0, top: 0, left: 0, description: "Sorry, ran out of time", link: undefined },
{ binnum: 1, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 2, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 3, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 4, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 5, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 6, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 7, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 8, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 9, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 10, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 11, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 12, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 13, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 14, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 15, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 16, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 17, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 18, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 19, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 20, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 21, top: 0, left: 0, description: "Dog Toys, Outer Shelf Bay", link: undefined },
{ binnum: 22, top: 0, left: 0, description: "Dog Toys, Outer shelf bay", link: undefined },
{ binnum: 23, top: 0, left: 0, description: "Shmackos, Outer shelf bay", link: undefined },
{ binnum: 24, top: 0, left: 0, description: "Dog Treats, Outer shelf bay", link: undefined },
{ binnum: 25, top: 0, left: 0, description: "Dog Treats, Outer Shelf Bay", link: undefined },
{ binnum: 26, top: 0, left: 0, description: "Dog Treats, Outer Shelf Bay", link: undefined },
{ binnum: 27, top: 0, left: 0, description: "Dog Food, Outer Shelf Bay", link: undefined },
{ binnum: 28, top: 0, left: 0, description: "Dog bowls, Outer Shelf Bay", link: undefined },
{ binnum: 29, top: 0, left: 0, description: "Puppy pads, Outer Shelf Bay", link: undefined },
{ binnum: 30, top: 0, left: 0, description: "Cat toys, Outer Shelf Bay", link: undefined },
{ binnum: 31, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 32, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 33, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 34, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 35, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 36, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 37, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 38, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 39, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 40, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 41, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 42, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 43, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 44, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 45, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 46, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 47, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 48, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 49, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 50, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 51, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 52, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 53, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 54, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 55, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 56, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 57, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 58, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 59, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 60, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 61, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 62, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 63, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 64, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 65, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 66, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 67, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 68, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 69, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 70, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 71, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 72, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 73, top: 0, left: 0, description: "Perimeter", link: undefined },
{ binnum: 74, top: 0, left: 0, description: "Behind the Registers", link: undefined },
{ binnum: 75, top: 0, left: 0, description: "Registers", link: undefined },
{ binnum: 76, top: 0, left: 0, description: "Registers", link: undefined },
{ binnum: 77, top: 0, left: 0, description: "Registers", link: undefined },
{ binnum: 78, top: 0, left: 0, description: "Confectionery, Registers", link: undefined },
{ binnum: 79, top: 0, left: 0, description: "Confectionery, Registers", link: undefined },
{ binnum: 80, top: 0, left: 0, description: "Confectionery, Registers", link: undefined },
{ binnum: 81, top: 0, left: 0, description: "Drink Fridge", link: undefined },
{ binnum: 82, top: 0, left: 0, description: "Gift cards, Registers", link: undefined },
{ binnum: 83, top: 0, left: 0, description: "Confectionery, Registers", link: undefined },
{ binnum: 84, top: 0, left: 0, description: "Confectionery, Registers", link: undefined },
{ binnum: 85, top: 0, left: 0, description: "Confectionery, Registers", link: undefined },
{ binnum: 86, top: 0, left: 0, description: "Confectionery, Registers", link: undefined },
{ binnum: 87, top: 0, left: 0, description: "Confectionary, Registers", link: undefined },
{ binnum: 88, top: 0, left: 0, description: "Popcorn, Registers", link: undefined },
{ binnum: 89, top: 0, left: 0, description: "Valentines Shelf, Registers", link: undefined },
{ binnum: 90, top: 0, left: 0, description: "Valentines Shelf, Registers", link: undefined },
{ binnum: 91, top: 0, left: 0, description: "Valentine shelf, Registers", link: undefined },
{ binnum: 92, top: 0, left: 0, description: "Batteries", link: undefined },
{ binnum: 93, top: 0, left: 0, description: "Batteries", link: undefined },
{ binnum: 94, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 95, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 96, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 97, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 98, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 99, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 100, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 101, top: 0, left: 0, description: "Two Tiers", link: undefined },
{ binnum: 102, top: 0, left: 0, description: "Umbrella Stand, FOH", link: undefined },
{ binnum: 103, top: 0, left: 0, description: "Sunglasses Stand, FOH", link: undefined },
{ binnum: 104, top: 0, left: 0, description: "Valentines Stand, FOH", link: undefined },
{ binnum: 105, top: 0, left: 0, description: "Batteries Stand, FOH", link: undefined },
{ binnum: 106, top: 0, left: 0, description: "Valentines Cards Stand, FOH", link: undefined },
{ binnum: 107, top: 0, left: 0, description: "Dump Bin", link: undefined },
{ binnum: 108, top: 0, left: 0, description: "Dump Bin", link: undefined },
{ binnum: 109, top: 0, left: 0, description: "Dump Bin", link: undefined },
{ binnum: 110, top: 0, left: 0, description: "Dump Bin", link: undefined },
{ binnum: 111, top: 0, left: 0, description: "Dump Bin", link: undefined },
{ binnum: 112, top: 0, left: 0, description: "Dump Bin", link: undefined },
{ binnum: 114, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 115, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 116, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 117, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 118, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 119, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 120, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 121, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 122, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 123, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 124, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 125, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 126, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 127, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 128, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 129, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 130, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 131, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 132, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 133, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 134, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 135, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 136, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 137, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 138, top: 0, left: 0, description: "Six Way", link: undefined },
{ binnum: 139, top: 0, left: 0, description: "Dog Pads, Floor Pallet", link: undefined },
{ binnum: 140, top: 0, left: 0, description: "Cat Litter, Floor Pallet", link: undefined },
{ binnum: 141, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 142, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 143, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 144, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 145, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 146, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 147, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 148, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 149, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 150, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 151, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 152, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 153, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 154, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 155, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 156, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 157, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 158, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 159, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 160, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 161, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 162, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 163, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 164, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 165, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 166, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 167, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 168, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 169, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 170, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 171, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 172, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 173, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 174, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 175, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 176, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 177, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 178, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 179, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 180, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 181, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 182, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 183, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 184, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 185, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 186, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 187, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 188, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 189, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 190, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 191, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 192, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 193, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 194, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 195, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 196, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 197, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 198, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 199, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 200, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 201, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 202, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 203, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 204, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 205, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 206, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 207, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 208, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 209, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 210, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 211, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 212, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 213, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 214, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 215, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 216, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 217, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 218, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 219, top: 0, left: 0, description: "Aisle", link: undefined },
{ binnum: 220, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 221, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 222, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 223, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 224, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 225, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 226, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 227, top: 0, left: 0, description: "Seeds", link: undefined },
{ binnum: 228, top: 0, left: 0, description: "Pots", link: undefined },
{ binnum: 229, top: 0, left: 0, description: "Pots (Officed)", link: undefined },
{ binnum: 230, top: 0, left: 0, description: "Pots (Officed)", link: undefined },
{ binnum: 231, top: 0, left: 0, description: "Pots", link: undefined },
{ binnum: 232, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 233, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 234, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 235, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 236, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 237, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 238, top: 0, left: 0, description: "Garden Aisle", link: undefined },
{ binnum: 239, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 240, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 241, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 242, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 243, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 244, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 245, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 246, top: 0, left: 0, description: "Pots", link: undefined },
{ binnum: 247, top: 0, left: 0, description: "Pots (Officed)", link: undefined },
{ binnum: 248, top: 0, left: 0, description: "Pots (Officed)", link: undefined },
{ binnum: 249, top: 0, left: 0, description: "Pots", link: undefined },
{ binnum: 250, top: 0, left: 0, description: "Pots (Officed)", link: undefined },
{ binnum: 251, top: 0, left: 0, description: "Pots (Officed)", link: undefined },
{ binnum: 252, top: 0, left: 0, description: "Container Bulk", link: undefined },
{ binnum: 253, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 254, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 255, top: 0, left: 0, description: "Toys Aisle", link: undefined },
{ binnum: 256, top: 0, left: 0, description: "Shower accessories Aisle", link: undefined },
{ binnum: 257, top: 0, left: 0, description: "Bathroom Aisle", link: undefined },
{ binnum: 258, top: 0, left: 0, description: "Bathroom Aisle", link: undefined },
{ binnum: 259, top: 0, left: 0, description: "Home Organisation Aisle", link: undefined },
{ binnum: 260, top: 0, left: 0, description: "Home Organisation Aisle", link: undefined },
{ binnum: 261, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 262, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 263, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 264, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 265, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 266, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 267, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 268, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 269, top: 0, left: 0, description: "Home Organisation", link: undefined },
{ binnum: 270, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 272, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 273, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 274, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 275, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 276, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 277, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 278, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 279, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 280, top: 0, left: 0, description: "Cleaning", link: undefined },
{ binnum: 281, top: 0, left: 0, description: "Kitchen, Cleaning End", link: undefined },
{ binnum: 282, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 283, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 284, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 285, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 286, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 287, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 288, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 289, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 290, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 291, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 292, top: 0, left: 0, description: "Cleaning Aisle", link: undefined },
{ binnum: 293, top: 0, left: 0, description: "Cleaning Back Stack", link: undefined },
{ binnum: 294, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 295, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 296, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 297, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 298, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 299, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 300, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 301, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 302, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 303, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 304, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 305, top: 0, left: 0, description: "Drinks, Kitchen End", link: undefined },
{ binnum: 306, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 307, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 308, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 309, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 310, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 311, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 312, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 313, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 314, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 315, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 316, top: 0, left: 0, description: "Kitchen Aisle", link: undefined },
{ binnum: 317, top: 0, left: 0, description: "Spin Mops, Kitchen Back Stack", link: undefined },
{ binnum: 318, top: 0, left: 0, description: "Photography, Home Deco Aisle", link: undefined },
{ binnum: 319, top: 0, left: 0, description: "Photography, Home Deco Aisle", link: undefined },
{ binnum: 320, top: 0, left: 0, description: "Photography, Home Deco Aisle", link: undefined },
{ binnum: 321, top: 0, left: 0, description: "Photography, Home Deco Aisle", link: undefined },
{ binnum: 322, top: 0, left: 0, description: "Photography, Home Deco Aisle", link: undefined },
{ binnum: 323, top: 0, left: 0, description: "Flowers, Home Deco Aisle", link: undefined },
{ binnum: 324, top: 0, left: 0, description: "Home Deco Aisle", link: undefined },
{ binnum: 325, top: 0, left: 0, description: "Home Deco Aisle", link: undefined },
{ binnum: 326, top: 0, left: 0, description: "Home Deco Aisle", link: undefined },
{ binnum: 327, top: 0, left: 0, description: "Home Deco Aisle", link: undefined },
{ binnum: 328, top: 0, left: 0, description: "Home Deco Aisle", link: undefined },
{ binnum: 329, top: 0, left: 0, description: "Party, Home Deco End", link: undefined },
{ binnum: 330, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 331, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 332, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 333, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 334, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 335, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 336, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 337, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 338, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 339, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 340, top: 0, left: 0, description: "Manchester Aisle", link: undefined },
{ binnum: 341, top: 0, left: 0, description: "Manchester Back Stack", link: undefined },
{ binnum: 342, top: 0, left: 0, description: "Aroma, Home Deco Aisle", link: undefined },
{ binnum: 343, top: 0, left: 0, description: "Aroma, Home Deco Aisle", link: undefined },
{ binnum: 344, top: 0, left: 0, description: "Candles, Home Deco Aisle", link: undefined },
{ binnum: 345, top: 0, left: 0, description: "Candles, Home Deco Aisle", link: undefined },
{ binnum: 346, top: 0, left: 0, description: "Candles, Home Deco Aisle", link: undefined },
{ binnum: 347, top: 0, left: 0, description: "Towels, Health and Beauty Aisle", link: undefined },
{ binnum: 348, top: 0, left: 0, description: "Footwear, Health and Beauty Aisle", link: undefined },
{ binnum: 349, top: 0, left: 0, description: "Footwear, Health and Beauty Aisle", link: undefined },
{ binnum: 350, top: 0, left: 0, description: "Footwear, Health and Beauty Aisle", link: undefined },
{ binnum: 351, top: 0, left: 0, description: "Footwear, Health and Beauty Aisle", link: undefined },
{ binnum: 352, top: 0, left: 0, description: "Footwear, Health and Beauty Aisle", link: undefined },
{ binnum: 353, top: 0, left: 0, description: "Australia Day, Health and Beauty End", link: undefined },
{ binnum: 354, top: 0, left: 0, description: "Card Stand", link: undefined },
{ binnum: 380, top: 0, left: 0, description: "Card Stand", link: undefined },
{ binnum: 381, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 382, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 383, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 384, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 385, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 386, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 387, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 388, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 389, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 390, top: 0, left: 0, description: "Card Drawers", link: undefined },
{ binnum: 391, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 392, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 393, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 394, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 395, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 396, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 397, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 398, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 399, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 400, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 401, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 402, top: 0, left: 0, description: "Side Stack", link: undefined },
{ binnum: 403, top: 0, left: 0, description: "Stationary Overhead", link: undefined },
{ binnum: 404, top: 0, left: 0, description: "Party Overhead", link: undefined },
{ binnum: 405, top: 0, left: 0, description: "Confectionary Overhead", link: undefined },
{ binnum: 406, top: 0, left: 0, description: "Confectionary Overhead", link: undefined },
{ binnum: 407, top: 0, left: 0, description: "Grocery Overhead", link: undefined },
{ binnum: 408, top: 0, left: 0, description: "Toiletries/Electrical Overhead", link: undefined },
{ binnum: 409, top: 0, left: 0, description: "Toiletries Overhead", link: undefined },
{ binnum: 410, top: 0, left: 0, description: "Manchester Overhead", link: undefined },
{ binnum: 411, top: 0, left: 0, description: "Kitchen Overhead", link: undefined },
{ binnum: 412, top: 0, left: 0, description: "Kitchen Overhead", link: undefined },
{ binnum: 413, top: 0, left: 0, description: "Cleaning Overhead", link: undefined },
{ binnum: 414, top: 0, left: 0, description: "Home Storage Overhead", link: undefined },
{ binnum: 415, top: 0, left: 0, description: "Home Organisation Overhead", link: undefined },
{ binnum: 416, top: 0, left: 0, description: "Home Deco Overhead", link: undefined },
{ binnum: 417, top: 0, left: 0, description: "Toys Overhead", link: undefined },
{ binnum: 418, top: 0, left: 0, description: "Clip Strip", link: undefined },
{ binnum: 419, top: 0, left: 0, description: "Misc", link: undefined },
{ binnum: 420, top: 0, left: 0, description: "Back of House / Markdown", link: undefined },
{ binnum: 421, top: 0, left: 0, description: "Back of House / Markdown (OFFICED)", link: undefined },
{ binnum: 422, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 423, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 424, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 425, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 426, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 427, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 428, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 429, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 430, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 431, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 432, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 433, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 434, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 435, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 436, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 437, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 438, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 439, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 440, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 441, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 442, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 443, top: 0, left: 0, description: "Cage", link: undefined },
{ binnum: 444, top: 0, left: 0, description: "Cards and party, Side Stack", link: undefined },
{ binnum: 445, top: 0, left: 0, description: "Registers, Side Stack", link: undefined },
{ binnum: 446, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 447, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 448, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 449, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 450, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 451, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 452, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 453, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 454, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 455, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 456, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 457, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 458, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 459, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 460, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 461, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 462, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 463, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 464, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 465, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 466, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 467, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 468, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 469, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 470, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 471, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 472, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 473, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 474, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 475, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 476, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 477, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 478, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 479, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 480, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 481, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 482, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 483, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 484, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 485, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 486, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 487, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 488, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 489, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 490, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 491, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 492, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 493, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 494, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 495, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 496, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 497, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 498, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 499, top: 0, left: 0, description: "Pallet", link: undefined },
{ binnum: 500, top: 0, left: 0, description: "Pallet", link: undefined },
];
binbox.addEventListener('input', function (e) {
    var num = Number(binbox.value)
    console.log(binbox.value)
    textbox.textContent = obj.find(function (x){return x.binnum ==num}).description
    /*obj[num-1].link.style.color= rgb(0, 255, 0);*/
})
/*
obj.forEach(function (item, index) {
    var span = document.createElement("span")
    span.className = "dot";
    span.style = "top: " + item.top.toString() + "%; left: " + item.left.toString() + "%;";
    span.textContent = item.binnum;
    obj[index].link = span
    document.getElementsByClassName("image-container")[0].appendChild(span)
})*/